import { createSlice } from '@reduxjs/toolkit';

export const CartSlice = createSlice({
  name: 'cart',
  initialState: {
    items: [], // each item: { name, cost, image, description, quantity, etc. }
  },
  reducers: {
    // 1) addItem:
    // Checks if the item is already in the cart by name.
    // If it exists, increment its quantity by 1.
    // Otherwise, push a new item with quantity=1.
    addItem: (state, action) => {
      const newItem = action.payload;
      const existingItem = state.items.find(
        (item) => item.name === newItem.name
      );

      if (existingItem) {
        // If item is already in the cart, increase quantity
        existingItem.quantity += 1;
      } else {
        // Otherwise, add the item with quantity=1
        state.items.push({ ...newItem, quantity: 1 });
      }
    },

    // 2) removeItem:
    // Removes an item from the cart by matching its name
    removeItem: (state, action) => {
      const name = action.payload; // e.g. "Snake Plant"
      state.items = state.items.filter((item) => item.name !== name);
    },

    // 3) updateQuantity:
    // Sets a new quantity for an existing item.
    // action.payload => { name: string, amount: number }
    updateQuantity: (state, action) => {
      const { name, amount } = action.payload;
      const existingItem = state.items.find((item) => item.name === name);

      if (existingItem) {
        existingItem.quantity = amount;
      }
    },
  },
});

// Action creators generated by createSlice
export const { addItem, removeItem, updateQuantity } = CartSlice.actions;

// Export the reducer for your store
export default CartSlice.reducer;
